project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    # - "costs.qmd"
    - "!model.qmd" # temporarily exclude model.qmd
    - "!international_model.qmd" # temporarily exclude international_model.qmd
    - "!_dump.qmd"

website:
  title: "Missing Middle Street Trees – YIMBY Melbourne"
  favicon: images/favicon.jpeg
  navbar:
    title: "Missing Middle Street Trees – YIMBY Melbourne"
    tools:
      - icon: twitter
        href: "#"
      - icon: instagram
        href: "#"
      - icon: linkedin
        href: "#"
      - icon: github
        href: "#"
      - icon: envelope
        href: "mailto:contact@yimby.melbourne"
    pinned: true
    tools-collapse: true
  sidebar:
    title: "Missing Middle Street Trees"
    logo: images/street-tree-og.jpg
    style: "floating"
    collapse-level: 1
    contents:
      - text: Missing Middle Street Trees
        href: index.qmd
      - text: Benefits of street trees
        href: benefits.qmd
      - text: Selecting & costing street trees
        href: costs.qmd
      - text: Your suburb's tree canopy
        href: suburbs.qmd
      - text: Additional data & analysis
        href: more-data.qmd
    # - section: "Model & methodology"
    #   contents:
    #     - text: Overview
    #       href: model-overview.qmd
    #     - text: Measuring Melbourne's street canopy
    #       href: model.qmd
    #     - text: Measuring international cities' tree canopy
    #       href: international_model.qmd
  search: false
  open-graph:
    image: https://trees.yimby.melbourne/images/street-tree-og.png
    title: "Missing Middle Street Trees"
    description: "The best time to plant a tree is 20 years ago. The second best time is when building more homes where people want to live."
  twitter-card:
    image: https://trees.yimby.melbourne/images/street-tree-og.png
    title: "Missing Middle Street Trees"
    description: "The best time to plant a tree is 20 years ago. The second best time is when building more homes where people want to live."
    card-style: summary_large_image
    site: "@yimbymelbourne"
    creator: "@yimbymelbourne"

format:
  html:
    theme: theme.scss
    # css: styles.scss
    toc: true
    toc-depth: 4
    fig-width: 8
    fig-height: 8
    code-fold: false
  # pdf:
  #   toc: true
  #   number-sections: true
  #   colorlinks: true
  #   pdf-engine: xelatex
  #   prefer-html: true
